# Generated by Django 3.0.4 on 2020-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
